import logging
import math
import os

import bpy
from bpy.types import Operator, WorkSpaceTool

from .domain.geometry import process_linear_measurement, process_plane_measurement
from .domain.measurements import AzimuthCorrection, MeasurementKind, Point3D, RawMeasurement
from .scene_measurements import (
    add_scene_measurement,
    delete_active_scene_measurement,
    ensure_default_scene_measure_layer,
    scene_measure_active_color,
    scene_measure_default_color,
    scene_measurement_code_color,
    scene_measurement_code_visible,
    scene_measurement_points,
    set_scene_measurement_points,
)


logger = logging.getLogger(__name__)

PICK_DISTANCE_PX = 14.0
HANDLE_DISTANCE_PX = 18.0
CLICK_SELECT_THRESHOLD_PX = 5.0
MIN_MEASUREMENT_LENGTH = 1.0e-6
ANGLE_ARC_SEGMENTS = 32
SNAP_VERTEX_DISTANCE_PX = 14.0
SNAP_EDGE_DISTANCE_PX = 14.0

#: Processed records reused across viewport redraws, keyed by point positions
#: and azimuth correction. Cleared on file load and whenever it grows past the
#: limit, which keeps it bounded without tracking individual edits.
RECORD_CACHE_LIMIT = 4096
_record_cache = {}

_overlay_handle_3d = None
_overlay_handle_2d = None
_active_preview = {
    "points": (),
    "snap": False,
    "snap_type": None,
    "hover": (-1, None, -1),
    "snap_location": None,
}
_polygon_preview = {
    "points": (),
    "current": None,
    "snap": False,
    "snap_type": None,
    "snap_location": None,
    "closing": False,
}

#: Custom toolbar artwork, generated by ``tools/build_tool_icons.py``.
ICON_DIRECTORY = os.path.join(os.path.dirname(__file__), "icons")

#: Used when the add-on runs from a copy without ``icons/``. The built-in ruler
#: is the wrong picture, but a wrong picture beats Blender's blank fallback.
FALLBACK_TOOL_ICON = "ops.view3d.ruler"


def tool_icon(name):
    """Path Blender should load a workspace tool icon from.

    ``ToolSelectPanelHelper`` resolves ``bl_icon`` with
    ``os.path.join(<blender datafiles>/icons, bl_icon + ".dat")``, and
    ``os.path.join`` discards the first argument when the second is absolute.
    Returning an absolute path without the extension is therefore how an add-on
    ships its own toolbar icons.
    """
    path = os.path.join(ICON_DIRECTORY, name)
    return path if os.path.isfile(path + ".dat") else FALLBACK_TOOL_ICON


class ScientiaMeasureWorkSpaceTool(WorkSpaceTool):
    bl_space_type = 'VIEW_3D'
    bl_context_mode = 'OBJECT'
    bl_idname = "scientiajoints.measure"
    bl_label = "Scientia Measure"
    bl_description = (
        "Create and edit ScientiaJoints measurements\n"
        "Drag empty space for a distance measurement\n"
        "Drag a point to edit it\n"
        "Drag a 2-point segment to pull out a plane point\n"
        "Click empty space or press Alt+A to deselect\n"
        "Ctrl temporarily toggles snapping to visible geometry"
    )
    bl_icon = tool_icon("scientiajoints.measure")
    bl_widget = None
    bl_keymap = (
        ("wm.scientia_measure_drag", {"type": 'LEFTMOUSE', "value": 'PRESS'}, None),
        ("wm.scientia_measure_drag", {"type": 'LEFTMOUSE', "value": 'PRESS', "ctrl": True}, None),
        ("wm.scientia_measure_delete_active", {"type": 'X', "value": 'PRESS'}, None),
        ("wm.scientia_measure_delete_active", {"type": 'DEL', "value": 'PRESS'}, None),
        ("wm.scientia_measure_deselect", {"type": 'A', "value": 'PRESS', "alt": True}, None),
    )

    def draw_settings(context, layout, tool):
        scene = getattr(context, "scene", None)
        if scene is None:
            return
        if hasattr(scene, "scientia_measure_show_labels"):
            layout.prop(scene, "scientia_measure_show_labels", text="Labels")
        if hasattr(scene, "scientia_measure_snap_by_default"):
            layout.prop(scene, "scientia_measure_snap_by_default", text="Snap")
        if hasattr(scene, "scientia_measure_show_linear"):
            layout.prop(scene, "scientia_measure_show_linear", text="", icon="MOD_EDGESPLIT", toggle=True)
        if hasattr(scene, "scientia_measure_show_planes"):
            layout.prop(scene, "scientia_measure_show_planes", text="", icon="SNAP_FACE", toggle=True)
        layout.operator("wm.scientia_measure_deselect", text="", icon="RESTRICT_SELECT_ON")
        layout.operator("wm.scientia_measure_delete_active", text="", icon="TRASH")


class ScientiaPolygonMeasureWorkSpaceTool(WorkSpaceTool):
    bl_space_type = 'VIEW_3D'
    bl_context_mode = 'OBJECT'
    bl_idname = "scientiajoints.polygon_measure"
    bl_label = "Scientia Polygon Plane"
    bl_description = (
        "Create an averaged plane from a closed polygon\n"
        "Click points around the fracture boundary\n"
        "Right click, Enter, Space, or the first point to finish\n"
        "Backspace / X / Del removes the last point, Esc cancels"
    )
    bl_icon = tool_icon("scientiajoints.polygon_measure")
    bl_widget = None
    bl_keymap = (
        ("wm.scientia_polygon_measure", {"type": 'LEFTMOUSE', "value": 'PRESS'}, None),
        ("wm.scientia_polygon_measure", {"type": 'LEFTMOUSE', "value": 'PRESS', "ctrl": True}, None),
        ("wm.scientia_measure_delete_active", {"type": 'X', "value": 'PRESS'}, None),
        ("wm.scientia_measure_delete_active", {"type": 'DEL', "value": 'PRESS'}, None),
        ("wm.scientia_measure_deselect", {"type": 'A', "value": 'PRESS', "alt": True}, None),
    )

    def draw_settings(context, layout, tool):
        scene = getattr(context, "scene", None)
        if scene is None:
            return
        if hasattr(scene, "scientia_measure_show_labels"):
            layout.prop(scene, "scientia_measure_show_labels", text="Labels")
        if hasattr(scene, "scientia_measure_snap_by_default"):
            layout.prop(scene, "scientia_measure_snap_by_default", text="Snap")
        if hasattr(scene, "scientia_measure_show_linear"):
            layout.prop(scene, "scientia_measure_show_linear", text="", icon="MOD_EDGESPLIT", toggle=True)
        if hasattr(scene, "scientia_measure_show_planes"):
            layout.prop(scene, "scientia_measure_show_planes", text="", icon="SNAP_FACE", toggle=True)


class ScientiaMeasureDragOperator(Operator):
    bl_idname = "wm.scientia_measure_drag"
    bl_label = "Scientia Measure Drag"
    bl_description = "Create or edit a ScientiaJoints measurement"
    bl_options = {'UNDO'}

    def invoke(self, context, event):
        if context.area.type != 'VIEW_3D':
            return {'PASS_THROUGH'}

        ensure_measure_overlay()
        ensure_default_scene_measure_layer(context.scene)
        self._mode = None
        self._measure_index = -1
        self._point_index = -1
        self._start_location = None
        self._depth_location = None
        self._drag_started = False
        self._mouse_start = (event.mouse_region_x, event.mouse_region_y)

        hit = _hit_measurement_part(context, event)
        _active_preview["hover"] = hit

        if hit[0] >= 0:
            active_index = getattr(context.scene, "scientia_active_measurement_index", -1)
            is_active_measurement = hit[0] == active_index
            _set_active_measurement(context.scene, hit[0])
            measurement = context.scene.scientia_measurements[hit[0]]
            points = [_vector(point) for point in scene_measurement_points(measurement)]

            if not is_active_measurement:
                self._mode = "select"
                self._measure_index = hit[0]
                self._depth_location = _average_point(points)
            elif hit[1] == "point":
                self._mode = "edit_point"
                self._measure_index = hit[0]
                self._point_index = hit[2]
                self._depth_location = points[hit[2]]
            elif hit[1] == "segment" and len(points) == 2:
                self._mode = "add_center"
                self._measure_index = hit[0]
                self._point_index = 1
                self._depth_location = (points[0] + points[1]) * 0.5
                _active_preview["points"] = (points[0], self._depth_location, points[1])
            else:
                self._mode = "select"
                self._measure_index = hit[0]
                self._depth_location = _average_point(points)
        else:
            snap = _snap_enabled(context.scene, event)
            point, snapped, snap_type = _mouse_to_world(context, event, None, snap)
            self._mode = "new"
            self._start_location = point
            self._depth_location = point
            _active_preview["points"] = (point, point)
            _active_preview["snap"] = snapped
            _active_preview["snap_type"] = snap_type
            _active_preview["snap_location"] = point if snapped else None

        _set_cursor(context, _cursor_for_state(_snap_enabled(context.scene, event), _active_preview["snap"], self._mode))
        context.window_manager.modal_handler_add(self)
        context.area.tag_redraw()
        return {'RUNNING_MODAL'}

    def modal(self, context, event):
        if context.area:
            context.area.tag_redraw()

        if event.type in {'ESC', 'RIGHTMOUSE'}:
            _reset_preview()
            _restore_cursor(context)
            return {'CANCELLED'}

        if event.type == 'MOUSEMOVE':
            self._handle_mousemove(context, event)
            return {'RUNNING_MODAL'}

        if event.type == 'LEFTMOUSE' and event.value == 'RELEASE':
            self._handle_release(context, event)
            _reset_preview()
            _restore_cursor(context)
            return {'FINISHED'}

        return {'PASS_THROUGH'}

    def _handle_mousemove(self, context, event):
        self._drag_started = True
        if self._mode == "select":
            _set_cursor(context, _cursor_for_state(_snap_enabled(context.scene, event), False, self._mode))
            return

        snap = _snap_enabled(context.scene, event)
        point, snapped, snap_type = _mouse_to_world(context, event, self._depth_location, snap)
        _active_preview["snap"] = snapped
        _active_preview["snap_type"] = snap_type
        _active_preview["snap_location"] = point if snapped else None
        _set_cursor(context, _cursor_for_state(snap, snapped, self._mode))

        if self._mode == "new":
            _active_preview["points"] = (self._start_location, point)
            return

        if self._mode == "edit_point":
            self._preview_existing_point(context, point)
            return

        if self._mode == "add_center":
            if 0 <= self._measure_index < len(context.scene.scientia_measurements):
                measurement = context.scene.scientia_measurements[self._measure_index]
                base = [_vector(item) for item in scene_measurement_points(measurement)]
                if len(base) == 2:
                    _active_preview["points"] = (base[0], point, base[1])

    def _handle_release(self, context, event):
        if self._mode == "select":
            return

        snap = _snap_enabled(context.scene, event)
        point, snapped, snap_type = _mouse_to_world(context, event, self._depth_location, snap)
        _active_preview["snap"] = snapped
        _active_preview["snap_type"] = snap_type
        _active_preview["snap_location"] = point if snapped else None

        if self._mode == "new":
            # A short click on empty space deselects instead of creating a
            # degenerate micro-measurement from cursor jitter.
            moved_px = math.hypot(
                event.mouse_region_x - self._mouse_start[0],
                event.mouse_region_y - self._mouse_start[1],
            )
            if moved_px < CLICK_SELECT_THRESHOLD_PX:
                _set_active_measurement(context.scene, -1)
                return
            if (_vector(point) - _vector(self._start_location)).length > MIN_MEASUREMENT_LENGTH:
                add_scene_measurement(context.scene, (self._start_location, point))
            return

        if self._mode == "edit_point":
            if 0 <= self._measure_index < len(context.scene.scientia_measurements):
                measurement = context.scene.scientia_measurements[self._measure_index]
                points = list(scene_measurement_points(measurement))
                if 0 <= self._point_index < len(points):
                    points[self._point_index] = point
                    set_scene_measurement_points(measurement, points)
                    _set_active_measurement(context.scene, self._measure_index)
            return

        if self._mode == "add_center":
            if 0 <= self._measure_index < len(context.scene.scientia_measurements):
                measurement = context.scene.scientia_measurements[self._measure_index]
                base = [_vector(item) for item in scene_measurement_points(measurement)]
                if len(base) == 2:
                    set_scene_measurement_points(measurement, (base[0], point, base[1]))
                    _set_active_measurement(context.scene, self._measure_index)

    def _preview_existing_point(self, context, point):
        if not (0 <= self._measure_index < len(context.scene.scientia_measurements)):
            return
        measurement = context.scene.scientia_measurements[self._measure_index]
        points = [_vector(item) for item in scene_measurement_points(measurement)]
        if not (0 <= self._point_index < len(points)):
            return
        points[self._point_index] = point
        _active_preview["points"] = tuple(points)


class ScientiaPolygonMeasureOperator(Operator):
    bl_idname = "wm.scientia_polygon_measure"
    bl_label = "Scientia Polygon Plane"
    bl_description = "Create a closed multi-point polygon plane measurement"
    bl_options = {'UNDO'}

    def invoke(self, context, event):
        if context.area.type != 'VIEW_3D':
            return {'PASS_THROUGH'}

        ensure_measure_overlay()
        ensure_default_scene_measure_layer(context.scene)
        _reset_preview()
        _reset_polygon_preview()
        self._mode = "create"
        self._measure_index = -1
        self._point_index = -1
        self._points = []
        self._depth_location = None

        hit = _hit_measurement_part(context, event)
        if hit[0] >= 0:
            active_index = getattr(context.scene, "scientia_active_measurement_index", -1)
            is_active_measurement = hit[0] == active_index
            _set_active_measurement(context.scene, hit[0])
            if not is_active_measurement or hit[1] != "point":
                context.area.tag_redraw()
                return {'FINISHED'}
            measurement = context.scene.scientia_measurements[hit[0]]
            points = [_vector(point) for point in scene_measurement_points(measurement)]
            if not (0 <= hit[2] < len(points)):
                context.area.tag_redraw()
                return {'FINISHED'}
            self._mode = "edit_point"
            self._measure_index = hit[0]
            self._point_index = hit[2]
            self._depth_location = points[hit[2]]
            _active_preview["points"] = tuple(points)
            _active_preview["hover"] = hit
            context.window_manager.modal_handler_add(self)
            context.area.tag_redraw()
            return {'RUNNING_MODAL'}

        self._add_point(context, event)
        context.window_manager.modal_handler_add(self)
        context.area.tag_redraw()
        return {'RUNNING_MODAL'}

    def modal(self, context, event):
        if context.area:
            context.area.tag_redraw()

        if event.type == 'ESC':
            _reset_polygon_preview()
            _reset_preview()
            _restore_cursor(context)
            return {'CANCELLED'}

        if event.type == 'RIGHTMOUSE':
            if event.value != 'PRESS':
                return {'RUNNING_MODAL'}
            # Right click finishes the polygon so the user does not have to
            # find the first point again; with too few points it cancels.
            if self._mode == "create" and len(self._points) >= 3:
                return self._finish(context)
            _reset_polygon_preview()
            _reset_preview()
            _restore_cursor(context)
            return {'CANCELLED'}

        if event.type in {'MIDDLEMOUSE', 'WHEELUPMOUSE', 'WHEELDOWNMOUSE', 'WHEELINMOUSE', 'WHEELOUTMOUSE'}:
            return {'PASS_THROUGH'}

        if event.type in {'RET', 'NUMPAD_ENTER', 'SPACE'} and event.value == 'PRESS':
            return self._finish(context)

        if event.type in {'BACK_SPACE', 'X', 'DEL'} and event.value == 'PRESS':
            if self._mode == "create":
                self._remove_last_point(context)
            return {'RUNNING_MODAL'}

        if event.type == 'MOUSEMOVE':
            if self._mode == "edit_point":
                self._preview_existing_point(context, event)
                return {'RUNNING_MODAL'}
            self._update_current(context, event)
            return {'RUNNING_MODAL'}

        if self._mode == "edit_point" and event.type == 'LEFTMOUSE' and event.value == 'RELEASE':
            self._commit_existing_point(context, event)
            _reset_preview()
            _restore_cursor(context)
            return {'FINISHED'}

        if self._mode == "edit_point":
            return {'RUNNING_MODAL'}

        if event.type == 'LEFTMOUSE' and event.value == 'PRESS':
            self._update_current(context, event)
            if _polygon_preview["closing"]:
                return self._finish(context)
            self._add_point(context, event)
            return {'RUNNING_MODAL'}

        return {'PASS_THROUGH'}

    def _add_point(self, context, event):
        point, snapped, snap_type = self._event_point(context, event)
        if self._points and (point - self._points[-1]).length <= MIN_MEASUREMENT_LENGTH:
            return
        self._points.append(point)
        self._depth_location = point
        _polygon_preview["points"] = tuple(self._points)
        _polygon_preview["current"] = point
        _polygon_preview["snap"] = snapped
        _polygon_preview["snap_type"] = snap_type
        _polygon_preview["snap_location"] = point if snapped else None
        _polygon_preview["closing"] = False
        _set_cursor(context, _cursor_for_state(_snap_enabled(context.scene, event), snapped, "polygon"))

    def _update_current(self, context, event):
        point, snapped, snap_type = self._event_point(context, event)
        closing = len(self._points) >= 3 and _screen_distance_to_point(context, event, self._points[0]) <= HANDLE_DISTANCE_PX
        if closing:
            point = self._points[0]
        _polygon_preview["points"] = tuple(self._points)
        _polygon_preview["current"] = point
        _polygon_preview["snap"] = snapped
        _polygon_preview["snap_type"] = snap_type
        _polygon_preview["snap_location"] = point if snapped else None
        _polygon_preview["closing"] = closing
        _set_cursor(context, _cursor_for_state(_snap_enabled(context.scene, event), snapped or closing, "polygon"))

    def _preview_existing_point(self, context, event):
        if not (0 <= self._measure_index < len(context.scene.scientia_measurements)):
            return
        measurement = context.scene.scientia_measurements[self._measure_index]
        points = [_vector(point) for point in scene_measurement_points(measurement)]
        if not (0 <= self._point_index < len(points)):
            return
        point, snapped, snap_type = self._event_point(context, event)
        points[self._point_index] = point
        _active_preview["points"] = tuple(points)
        _active_preview["snap"] = snapped
        _active_preview["snap_type"] = snap_type
        _active_preview["snap_location"] = point if snapped else None
        _set_cursor(context, _cursor_for_state(_snap_enabled(context.scene, event), snapped, "edit_point"))

    def _commit_existing_point(self, context, event):
        if not (0 <= self._measure_index < len(context.scene.scientia_measurements)):
            return
        measurement = context.scene.scientia_measurements[self._measure_index]
        points = list(scene_measurement_points(measurement))
        if not (0 <= self._point_index < len(points)):
            return
        point, snapped, snap_type = self._event_point(context, event)
        points[self._point_index] = point
        set_scene_measurement_points(measurement, points)
        _active_preview["snap"] = snapped
        _active_preview["snap_type"] = snap_type
        _active_preview["snap_location"] = point if snapped else None
        _set_active_measurement(context.scene, self._measure_index)

    def _event_point(self, context, event):
        snap = _snap_enabled(context.scene, event)
        depth = self._depth_location
        if depth is None and self._points:
            depth = self._points[-1]
        return _mouse_to_world(context, event, depth, snap)

    def _remove_last_point(self, context):
        if self._points:
            self._points.pop()
        if not self._points:
            _reset_polygon_preview()
            _restore_cursor(context)
            return
        self._depth_location = self._points[-1]
        _polygon_preview["points"] = tuple(self._points)
        _polygon_preview["current"] = self._points[-1]
        _polygon_preview["closing"] = False

    def _finish(self, context):
        if len(self._points) < 3:
            self.report({'WARNING'}, "At least three polygon points are required.")
            _reset_polygon_preview()
            _restore_cursor(context)
            return {'CANCELLED'}
        add_scene_measurement(context.scene, tuple(self._points), kind="POLYLINE")
        _reset_polygon_preview()
        _restore_cursor(context)
        _tag_view3d_redraw(context)
        return {'FINISHED'}


class ScientiaDeleteActiveMeasurementOperator(Operator):
    bl_idname = "wm.scientia_measure_delete_active"
    bl_label = "Delete Measurement"
    bl_description = "Delete the active ScientiaJoints measurement"
    bl_options = {'UNDO'}

    def execute(self, context):
        if delete_active_scene_measurement(context.scene):
            _tag_view3d_redraw(context)
            return {'FINISHED'}
        self.report({'WARNING'}, "No active Scientia measurement to delete.")
        return {'CANCELLED'}


class ScientiaDeselectMeasurementOperator(Operator):
    bl_idname = "wm.scientia_measure_deselect"
    bl_label = "Deselect Measurement"
    bl_description = "Clear the active ScientiaJoints measurement selection"
    bl_options = {'UNDO'}

    def execute(self, context):
        scene = context.scene
        if not hasattr(scene, "scientia_measurements"):
            return {'CANCELLED'}
        _set_active_measurement(scene, -1)
        _tag_view3d_redraw(context)
        return {'FINISHED'}


def ensure_measure_overlay():
    global _overlay_handle_3d, _overlay_handle_2d
    if _overlay_handle_3d is None:
        _overlay_handle_3d = bpy.types.SpaceView3D.draw_handler_add(
            _draw_measurements_3d,
            (),
            'WINDOW',
            'POST_VIEW',
        )
    if _overlay_handle_2d is None:
        _overlay_handle_2d = bpy.types.SpaceView3D.draw_handler_add(
            _draw_measurements_2d,
            (),
            'WINDOW',
            'POST_PIXEL',
        )


def remove_measure_overlay():
    global _overlay_handle_3d, _overlay_handle_2d
    if _overlay_handle_3d is not None:
        bpy.types.SpaceView3D.draw_handler_remove(_overlay_handle_3d, 'WINDOW')
        _overlay_handle_3d = None
    if _overlay_handle_2d is not None:
        bpy.types.SpaceView3D.draw_handler_remove(_overlay_handle_2d, 'WINDOW')
        _overlay_handle_2d = None
    reset_tool_state()


def overlay_is_active():
    return _overlay_handle_3d is not None and _overlay_handle_2d is not None


def reset_tool_state():
    """Drop every piece of state that belongs to the previous .blend file.

    The preview dictionaries and the record cache live at module level, so
    without this a freshly loaded file inherits the ghost preview and the
    cached geometry of the file that was open before.
    """
    _reset_preview()
    _reset_polygon_preview()
    clear_record_cache()


#: The toolbar identifiers this add-on owns. Nothing else may use them, so
#: removing an entry that carries one can never touch another add-on's tool.
TOOL_IDNAMES = (
    ScientiaMeasureWorkSpaceTool.bl_idname,
    ScientiaPolygonMeasureWorkSpaceTool.bl_idname,
)


def _toolbar_tool_lists():
    """Blender's per-mode tool lists for the 3D View toolbar."""
    from bl_ui.space_toolsystem_common import ToolSelectPanelHelper

    helper = ToolSelectPanelHelper._tool_class_from_space_type('VIEW_3D')
    if helper is None:
        return ()
    return tuple(helper._tools.values())


def _drop_stray_separators(tools):
    """Trim the separator entries a removal can leave behind."""
    while tools and tools[0] is None:
        del tools[0]
    while tools and tools[-1] is None:
        del tools[-1]
    for index in range(len(tools) - 1, 0, -1):
        if tools[index] is None and tools[index - 1] is None:
            del tools[index]


def _remove_tool_keymap(tool_def):
    """Remove the key-map ``register_tool`` created for a tool definition.

    After registration ``ToolDef.keymap`` is a one-item list holding the
    generated key-map name, which is what Blender's own ``unregister_tool``
    looks up. Before registration it still holds the callback, so anything
    that is not a string is left alone.
    """
    keymap = getattr(tool_def, "keymap", None)
    if not keymap or not isinstance(keymap[0], str):
        return
    keyconfigs = bpy.context.window_manager.keyconfigs
    for keyconfig in (keyconfigs.default, keyconfigs.addon):
        if keyconfig is None:
            continue
        existing = keyconfig.keymaps.get(keymap[0])
        if existing is not None:
            keyconfig.keymaps.remove(existing)


def purge_registered_tools(idnames=TOOL_IDNAMES):
    """Remove toolbar entries for ``idnames``, whoever registered them.

    ``bpy.utils.unregister_tool()`` finds the entry by the exact ``ToolDef``
    object it stored on the class as ``_bl_tool``, so it cannot remove one left
    by a *different* copy of this module. That happens when the add-on is
    installed twice, as an extension and as a legacy add-on, and when a reload
    drops the old classes from ``sys.modules`` before ``unregister()`` runs.
    Blender then refuses the fresh registration with
    ``Tool 'scientiajoints.measure' already exists!`` and the add-on fails to
    enable at all.

    Returns the identifiers that were actually removed.
    """
    # ToolDef is itself a namedtuple, so it has to be recognised before the
    # plain tuple that marks a nested group; isinstance(item, tuple) is true
    # for both, and treating a tool as a group iterates its fields instead.
    from bl_ui.space_toolsystem_common import ToolDef

    removed = []

    def keep(entry):
        if getattr(entry, "idname", None) not in idnames:
            return True
        removed.append(entry.idname)
        _remove_tool_keymap(entry)
        return False

    for tools in _toolbar_tool_lists():
        for index in range(len(tools) - 1, -1, -1):
            item = tools[index]
            if item is None:
                continue
            if isinstance(item, ToolDef):
                if not keep(item):
                    del tools[index]
            elif isinstance(item, tuple):
                kept = [sub for sub in item if sub is None or keep(sub)]
                if len(kept) == len(item):
                    continue
                _drop_stray_separators(kept)
                if kept:
                    tools[index] = tuple(kept)
                else:
                    del tools[index]
        _drop_stray_separators(tools)

    return tuple(removed)


def register_measure_tool():
    for tool in (ScientiaPolygonMeasureWorkSpaceTool, ScientiaMeasureWorkSpaceTool):
        try:
            bpy.utils.unregister_tool(tool)
        except Exception:
            pass
    try:
        leftover = purge_registered_tools()
    except Exception as e:
        leftover = ()
        logger.debug("Could not inspect the 3D View toolbar: %s", e)
    if leftover:
        logger.warning(
            "Removed a leftover toolbar entry for %s before registering. This means an earlier "
            "ScientiaJoints registration was not cleaned up, or the add-on is installed twice - "
            "as an extension and as a legacy add-on. Keep only one installation.",
            ", ".join(sorted(set(leftover))),
        )
    try:
        bpy.utils.register_tool(ScientiaMeasureWorkSpaceTool, after={"builtin.measure"}, separator=True)
    except Exception:
        bpy.utils.register_tool(ScientiaMeasureWorkSpaceTool, after={"builtin.cursor"}, separator=True)
    try:
        bpy.utils.register_tool(ScientiaPolygonMeasureWorkSpaceTool, after={"scientiajoints.measure"}, separator=False)
    except Exception:
        bpy.utils.register_tool(ScientiaPolygonMeasureWorkSpaceTool, after={"builtin.measure"}, separator=True)
    ensure_measure_overlay()


def unregister_measure_tool():
    for tool in (ScientiaPolygonMeasureWorkSpaceTool, ScientiaMeasureWorkSpaceTool):
        try:
            bpy.utils.unregister_tool(tool)
        except Exception:
            pass
    # Belt and braces: an entry whose class object no longer matches survives
    # the calls above and would block the next registration.
    try:
        purge_registered_tools()
    except Exception as e:
        logger.debug("Could not clean the 3D View toolbar: %s", e)
    remove_measure_overlay()


def _mouse_to_world(context, event, depth_location=None, snap=False):
    from bpy_extras import view3d_utils
    from mathutils import Vector

    region = context.region
    rv3d = context.region_data
    coord = (event.mouse_region_x, event.mouse_region_y)

    if snap:
        origin = view3d_utils.region_2d_to_origin_3d(region, rv3d, coord)
        direction = view3d_utils.region_2d_to_vector_3d(region, rv3d, coord)
        try:
            depsgraph = context.evaluated_depsgraph_get()
            hit, location, _normal, index, obj, matrix = context.scene.ray_cast(
                depsgraph,
                origin,
                direction,
            )
            if hit:
                snap_location, snap_type = _classified_snap_location(
                    context,
                    event,
                    location,
                    obj,
                    matrix,
                    index,
                )
                return snap_location.copy(), True, snap_type
        except Exception:
            pass

    if depth_location is None:
        cursor = getattr(context.scene, "cursor", None)
        depth_location = getattr(cursor, "location", Vector((0.0, 0.0, 0.0)))

    return view3d_utils.region_2d_to_location_3d(region, rv3d, coord, depth_location), False, None


def _classified_snap_location(context, event, location, obj, matrix, polygon_index):
    from bpy_extras import view3d_utils
    from mathutils import Vector

    if obj is None or polygon_index < 0:
        return location, "FACE"

    mesh = getattr(obj, "data", None)
    if mesh is None or not hasattr(mesh, "polygons") or polygon_index >= len(mesh.polygons):
        return location, "FACE"

    world_matrix = matrix if matrix is not None else obj.matrix_world
    polygon = mesh.polygons[polygon_index]
    mouse = Vector((event.mouse_region_x, event.mouse_region_y))

    vertex_candidates = []
    for vertex_index in polygon.vertices:
        vertex = world_matrix @ mesh.vertices[vertex_index].co
        vertex_2d = view3d_utils.location_3d_to_region_2d(context.region, context.region_data, vertex)
        if vertex_2d is None:
            continue
        vertex_candidates.append(((mouse - vertex_2d).length, vertex))

    if vertex_candidates:
        distance, vertex = min(vertex_candidates, key=lambda item: item[0])
        if distance <= SNAP_VERTEX_DISTANCE_PX:
            return vertex, "VERTEX"

    edge_candidates = []
    vertices = list(polygon.vertices)
    for index, vertex_index in enumerate(vertices):
        next_index = vertices[(index + 1) % len(vertices)]
        start = world_matrix @ mesh.vertices[vertex_index].co
        end = world_matrix @ mesh.vertices[next_index].co
        closest = _closest_point_on_segment(location, start, end)
        closest_2d = view3d_utils.location_3d_to_region_2d(context.region, context.region_data, closest)
        if closest_2d is None:
            continue
        edge_candidates.append(((mouse - closest_2d).length, closest))

    if edge_candidates:
        distance, closest = min(edge_candidates, key=lambda item: item[0])
        if distance <= SNAP_EDGE_DISTANCE_PX:
            return closest, "EDGE"

    return location, "FACE"


def _hit_measurement_part(context, event):
    from bpy_extras import view3d_utils
    from mathutils import Vector

    scene = context.scene
    if not hasattr(scene, "scientia_measurements"):
        return (-1, None, -1)

    mouse = Vector((event.mouse_region_x, event.mouse_region_y))
    best_point = (-1, None, -1)
    best_point_distance = HANDLE_DISTANCE_PX
    best_segment = (-1, None, -1)
    best_segment_distance = PICK_DISTANCE_PX

    for index, measurement in enumerate(scene.scientia_measurements):
        if not _measurement_visible(scene, measurement, index):
            continue
        points = [_vector(point.co) for point in measurement.points]
        if len(points) < 2:
            continue

        for point_index, point in enumerate(points):
            point_2d = view3d_utils.location_3d_to_region_2d(context.region, context.region_data, point)
            if point_2d is None:
                continue
            distance = (mouse - point_2d).length
            if distance < best_point_distance:
                best_point_distance = distance
                best_point = (index, "point", point_index)

        for segment_index, (start, end) in enumerate(_segments(points, closed=_measurement_is_polygon(measurement, points))):
            start_2d = view3d_utils.location_3d_to_region_2d(context.region, context.region_data, start)
            end_2d = view3d_utils.location_3d_to_region_2d(context.region, context.region_data, end)
            if start_2d is None or end_2d is None:
                continue
            distance = _distance_to_segment_2d(mouse, start_2d, end_2d)
            if distance < best_segment_distance:
                best_segment_distance = distance
                best_segment = (index, "segment", segment_index)

    if best_point[0] >= 0:
        return best_point
    return best_segment


def _set_active_measurement(scene, active_index):
    for index, measurement in enumerate(scene.scientia_measurements):
        measurement.selected = index == active_index
    scene.scientia_active_measurement_index = active_index


def _draw_measurements_3d():
    context = bpy.context
    scene = getattr(context, "scene", None)
    if scene is None or not hasattr(scene, "scientia_measurements"):
        return

    import gpu
    from gpu_extras.batch import batch_for_shader

    shader = _uniform_color_shader(gpu)
    if shader is None:
        return

    try:
        gpu.state.blend_set('ALPHA')
        gpu.state.line_width_set(2.0)
        gpu.state.point_size_set(7.0)
    except Exception:
        pass

    line_groups = {}
    for index, measurement in enumerate(scene.scientia_measurements):
        if not _measurement_visible(scene, measurement, index):
            continue
        points = [_vector(point.co) for point in measurement.points]
        color = _measurement_color(measurement, index, scene)
        coords = line_groups.setdefault(color, [])
        coords.extend(_point_chain_coords(points, closed=_measurement_is_polygon(measurement, points)))
        coords.extend(_angle_arc_coords(points))

    for color, coords in line_groups.items():
        _draw_line_coords(shader, batch_for_shader, coords, color)

    if _active_preview["points"]:
        preview_color = (1.0, 0.85, 0.15, 1.0) if not _active_preview["snap"] else (0.2, 1.0, 0.35, 1.0)
        points = list(_active_preview["points"])
        _draw_point_chain(shader, batch_for_shader, points, preview_color)
        _draw_angle_arc(shader, batch_for_shader, points, preview_color)

    polygon_points = _polygon_preview_points(include_current=True)
    if polygon_points:
        polygon_color = (1.0, 0.85, 0.15, 1.0) if not _polygon_preview["snap"] else (0.2, 1.0, 0.35, 1.0)
        _draw_point_chain(shader, batch_for_shader, polygon_points, polygon_color, closed=len(polygon_points) >= 3)

    try:
        gpu.state.line_width_set(1.0)
        gpu.state.point_size_set(1.0)
        gpu.state.blend_set('NONE')
    except Exception:
        pass


def _draw_measurements_2d():
    context = bpy.context
    scene = getattr(context, "scene", None)
    if scene is None or not hasattr(scene, "scientia_measurements"):
        return

    import blf
    import gpu
    from gpu_extras.batch import batch_for_shader
    from bpy_extras import view3d_utils

    shader = _uniform_color_shader(gpu)
    if shader is not None:
        try:
            gpu.state.blend_set('ALPHA')
            gpu.state.line_width_set(1.5)
        except Exception:
            pass

        for index in _handle_measurement_indices(scene):
            if index < 0 or index >= len(scene.scientia_measurements):
                continue
            measurement = scene.scientia_measurements[index]
            if not _measurement_visible(scene, measurement, index):
                continue
            points = [_vector(point.co) for point in measurement.points]
            color = _measurement_color(measurement, index, scene)
            _draw_screen_handles(context, view3d_utils, shader, batch_for_shader, points, color, index, scene)

        if _active_preview["points"]:
            preview_color = (1.0, 0.85, 0.15, 1.0) if not _active_preview["snap"] else (0.2, 1.0, 0.35, 1.0)
            _draw_screen_handles(
                context,
                view3d_utils,
                shader,
                batch_for_shader,
                list(_active_preview["points"]),
                preview_color,
                -1,
                scene,
            )

        if _active_preview["snap_location"] is not None:
            _draw_snap_marker_2d(
                context,
                view3d_utils,
                shader,
                batch_for_shader,
                _active_preview["snap_location"],
                _active_preview["snap_type"],
            )

        polygon_points = _polygon_preview_points(include_current=True)
        if polygon_points:
            polygon_color = (1.0, 0.85, 0.15, 1.0) if not _polygon_preview["snap"] else (0.2, 1.0, 0.35, 1.0)
            _draw_screen_handles(
                context,
                view3d_utils,
                shader,
                batch_for_shader,
                polygon_points,
                polygon_color,
                -1,
                scene,
            )

        if _polygon_preview["snap_location"] is not None:
            _draw_snap_marker_2d(
                context,
                view3d_utils,
                shader,
                batch_for_shader,
                _polygon_preview["snap_location"],
                _polygon_preview["snap_type"],
            )

        try:
            gpu.state.line_width_set(1.0)
            gpu.state.blend_set('NONE')
        except Exception:
            pass

    if not getattr(scene, "scientia_measure_show_labels", True):
        return

    font_id = 0
    try:
        blf.size(font_id, 12)
    except TypeError:
        blf.size(font_id, 12, 72)

    for index, measurement in enumerate(scene.scientia_measurements):
        if not _measurement_visible(scene, measurement, index):
            continue
        points = [_vector(point.co) for point in measurement.points]
        _draw_label(context, view3d_utils, blf, font_id, points, measurement)

    if _active_preview["points"]:
        _draw_label(context, view3d_utils, blf, font_id, list(_active_preview["points"]))

    polygon_points = _polygon_preview_points(include_current=True)
    if len(polygon_points) >= 3:
        _draw_label(context, view3d_utils, blf, font_id, polygon_points)


def _draw_point_chain(shader, batch_for_shader, points, color, closed=False):
    _draw_line_coords(shader, batch_for_shader, _point_chain_coords(points, closed=closed), color)


def _point_chain_coords(points, closed=False):
    coords = []
    if len(points) < 2:
        return coords
    for start, end in _segments(points, closed=closed):
        coords.extend((start, end))
    return coords


def _draw_line_coords(shader, batch_for_shader, coords, color):
    if not coords:
        return
    batch = batch_for_shader(shader, 'LINES', {"pos": coords})
    shader.bind()
    shader.uniform_float("color", color)
    batch.draw(shader)


def _draw_screen_handles(context, view3d_utils, shader, batch_for_shader, points, color, measurement_index, scene):
    if not points:
        return

    active_index = getattr(scene, "scientia_active_measurement_index", -1)
    hover_index, hover_part, hover_point = _active_preview["hover"]
    is_active_measurement = measurement_index == active_index or measurement_index < 0

    for point_index, point in enumerate(points):
        position = view3d_utils.location_3d_to_region_2d(context.region, context.region_data, point)
        if position is None:
            continue

        is_hovered = (
            measurement_index == hover_index
            and hover_part == "point"
            and hover_point == point_index
        )
        size = 6.5
        if is_active_measurement:
            size = 8.0
        if is_hovered:
            size = 10.0

        if len(points) == 3 and point_index == 1:
            _draw_handle_circle_2d(shader, batch_for_shader, position, color, size, is_active_measurement, is_hovered)
        else:
            _draw_handle_square_2d(shader, batch_for_shader, position, color, size, is_active_measurement, is_hovered)


def _draw_snap_marker_2d(context, view3d_utils, shader, batch_for_shader, point, snap_type):
    position = view3d_utils.location_3d_to_region_2d(context.region, context.region_data, point)
    if position is None:
        return

    marker_type = snap_type or "FACE"
    color = (0.2, 1.0, 0.35, 1.0)
    if marker_type == "VERTEX":
        _draw_square_outline_2d(shader, batch_for_shader, position, 8.0, (0.0, 0.0, 0.0, 0.95), 3.0)
        _draw_square_outline_2d(shader, batch_for_shader, position, 8.0, color, 1.5)
    elif marker_type == "EDGE":
        _draw_hourglass_2d(shader, batch_for_shader, position, 9.0, (0.0, 0.0, 0.0, 0.95), 3.0)
        _draw_hourglass_2d(shader, batch_for_shader, position, 9.0, color, 1.5)
    else:
        _draw_circle_outline_2d(shader, batch_for_shader, position, 8.0, (0.0, 0.0, 0.0, 0.95), 3.0)
        _draw_circle_outline_2d(shader, batch_for_shader, position, 8.0, color, 1.5)


def _draw_handle_square_2d(shader, batch_for_shader, position, color, size, active, hovered):
    fill = (1.0, 1.0, 1.0, 1.0) if hovered else color
    if active and not hovered:
        fill = (1.0, 0.9, 0.2, 1.0)

    _draw_filled_square_2d(shader, batch_for_shader, position, size + 3.5, (0.0, 0.0, 0.0, 0.85))
    _draw_filled_square_2d(shader, batch_for_shader, position, size, fill)
    _draw_square_outline_2d(shader, batch_for_shader, position, size + 0.5, (1.0, 1.0, 1.0, 0.95), 1.0)


def _draw_handle_circle_2d(shader, batch_for_shader, position, color, size, active, hovered):
    outline_color = (1.0, 1.0, 1.0, 1.0) if hovered else color
    if active and not hovered:
        outline_color = (1.0, 0.9, 0.2, 1.0)

    _draw_circle_outline_2d(shader, batch_for_shader, position, size + 2.5, (0.0, 0.0, 0.0, 0.9), 3.0)
    _draw_circle_outline_2d(shader, batch_for_shader, position, size, outline_color, 2.0)
    _draw_cross_2d(shader, batch_for_shader, position, size * 0.65, (1.0, 1.0, 1.0, 0.95), 1.0)


def _draw_filled_square_2d(shader, batch_for_shader, position, size, color):
    x = float(position.x)
    y = float(position.y)
    half = size * 0.5
    coords = (
        (x - half, y - half),
        (x + half, y - half),
        (x + half, y + half),
        (x - half, y + half),
    )
    indices = ((0, 1, 2), (0, 2, 3))
    batch = batch_for_shader(shader, 'TRIS', {"pos": coords}, indices=indices)
    shader.bind()
    shader.uniform_float("color", color)
    batch.draw(shader)


def _draw_square_outline_2d(shader, batch_for_shader, position, size, color, width=1.0):
    x = float(position.x)
    y = float(position.y)
    half = size * 0.5
    coords = (
        (x - half, y - half), (x + half, y - half),
        (x + half, y - half), (x + half, y + half),
        (x + half, y + half), (x - half, y + half),
        (x - half, y + half), (x - half, y - half),
    )
    _draw_2d_lines(shader, batch_for_shader, coords, color, width)


def _draw_circle_outline_2d(shader, batch_for_shader, position, radius, color, width=1.0):
    x = float(position.x)
    y = float(position.y)
    segments = 28
    coords = []
    for index in range(segments):
        angle_a = math.tau * index / segments
        angle_b = math.tau * (index + 1) / segments
        coords.append((x + math.cos(angle_a) * radius, y + math.sin(angle_a) * radius))
        coords.append((x + math.cos(angle_b) * radius, y + math.sin(angle_b) * radius))
    _draw_2d_lines(shader, batch_for_shader, coords, color, width)


def _draw_hourglass_2d(shader, batch_for_shader, position, size, color, width=1.0):
    x = float(position.x)
    y = float(position.y)
    half = size * 0.5
    coords = (
        (x - half, y + half), (x + half, y + half),
        (x - half, y + half), (x, y),
        (x + half, y + half), (x, y),
        (x - half, y - half), (x + half, y - half),
        (x - half, y - half), (x, y),
        (x + half, y - half), (x, y),
    )
    _draw_2d_lines(shader, batch_for_shader, coords, color, width)


def _draw_cross_2d(shader, batch_for_shader, position, size, color, width=1.0):
    x = float(position.x)
    y = float(position.y)
    half = size * 0.5
    coords = (
        (x - half, y), (x + half, y),
        (x, y - half), (x, y + half),
    )
    _draw_2d_lines(shader, batch_for_shader, coords, color, width)


def _draw_2d_lines(shader, batch_for_shader, coords, color, width=1.0):
    import gpu

    try:
        gpu.state.line_width_set(width)
    except Exception:
        pass
    batch = batch_for_shader(shader, 'LINES', {"pos": coords})
    shader.bind()
    shader.uniform_float("color", color)
    batch.draw(shader)


def _draw_angle_arc(shader, batch_for_shader, points, color):
    _draw_line_coords(shader, batch_for_shader, _angle_arc_coords(points), color)


def _angle_arc_coords(points):
    if len(points) != 3:
        return []
    arc_points = _angle_arc_points(points[0], points[1], points[2])
    if len(arc_points) < 2:
        return []
    coords = []
    for index in range(len(arc_points) - 1):
        coords.extend((arc_points[index], arc_points[index + 1]))
    return coords


def _draw_label(context, view3d_utils, blf, font_id, points, measurement=None):
    if len(points) < 2:
        return
    label, anchor = _measurement_label(points, context.scene, measurement)
    if not label:
        return
    position = view3d_utils.location_3d_to_region_2d(context.region, context.region_data, anchor)
    if position is None:
        return
    lines = str(label).splitlines()
    text_x = position.x + 6
    text_y = position.y + 6
    if getattr(context.scene, "scientia_measure_label_background", True):
        _draw_label_background_2d(blf, font_id, lines, text_x, text_y)
    for line_index, line in enumerate(lines):
        blf.position(font_id, text_x, text_y - line_index * 14, 0)
        blf.draw(font_id, line)


def _measurement_label(points, scene=None, measurement=None):
    if len(points) == 2:
        start, end = points
        return "\n".join(_linear_label_lines(points, scene, measurement)), (start + end) * 0.5
    if len(points) >= 3:
        anchor = points[1] if len(points) == 3 else _average_point(list(points))
        return "\n".join(_plane_label_lines(tuple(points), scene, measurement)), anchor
    return "", None


def _linear_label_lines(points, scene, measurement):
    lines = _metadata_label_lines(scene, measurement)
    start, end = points[:2]
    record = active_linear_record_from_points(points, scene, measurement) if scene is not None else None

    length = record.length if record is not None else (end - start).length
    line = record.line_orientation if record is not None else None
    dx = end.x - start.x
    dy = end.y - start.y
    dz = end.z - start.z
    horizontal = math.sqrt(dx * dx + dy * dy)

    if _label_enabled(scene, "scientia_label_linear_distance", True):
        lines.append(f"distance {length:.3f}")
    if line is not None and _label_enabled(scene, "scientia_label_linear_angle", False):
        lines.append(f"angle {line.dip:.1f}")
    if line is not None and _label_enabled(scene, "scientia_label_linear_azimuth", False):
        lines.append(f"az {line.rotated_azimuth:.1f}")
    if line is not None and _label_enabled(scene, "scientia_label_linear_raw_azimuth", False):
        lines.append(f"raw az {line.azimuth:.1f}")
    if _label_enabled(scene, "scientia_label_linear_dx", False):
        lines.append(f"dx {dx:.3f}")
    if _label_enabled(scene, "scientia_label_linear_dy", False):
        lines.append(f"dy {dy:.3f}")
    if _label_enabled(scene, "scientia_label_linear_dz", False):
        lines.append(f"dz {dz:.3f}")
    if _label_enabled(scene, "scientia_label_linear_horizontal", False):
        lines.append(f"horizontal {horizontal:.3f}")
    return lines


def _plane_label_lines(points, scene, measurement):
    lines = _metadata_label_lines(scene, measurement)
    record = active_plane_record_from_points(points, scene, measurement) if scene is not None else None
    plane = record.plane_orientation if record is not None else None

    if plane is not None:
        show_dip = _label_enabled(scene, "scientia_label_plane_dip", True)
        show_azimuth = _label_enabled(scene, "scientia_label_plane_azimuth", True)
        if show_dip and show_azimuth:
            lines.append(f"dip {plane.dip:.1f} az {plane.rotated_azimuth:.1f}")
        elif show_dip:
            lines.append(f"dip {plane.dip:.1f}")
        elif show_azimuth:
            lines.append(f"az {plane.rotated_azimuth:.1f}")
        if _label_enabled(scene, "scientia_label_plane_raw_azimuth", False):
            lines.append(f"raw az {plane.azimuth:.1f}")

    if _label_enabled(scene, "scientia_label_plane_angle", False):
        if record is not None and record.degree is not None:
            lines.append(f"angle {record.degree:.1f} deg")
        elif record is None:
            lines.append(f"angle {_point_angle_degrees(points):.1f} deg")
    if record is not None and _label_enabled(scene, "scientia_label_plane_area", False):
        lines.append(f"area {record.area:.4f}")
    if (
        record is not None
        and len(points) > 3
        and record.fit_error is not None
        and _label_enabled(scene, "scientia_label_plane_fit_error", True)
    ):
        lines.append(
            f"fit err {record.fit_error:.3f} ({record.fit_error_relative * 100:.1f}%)"
        )
    return lines


def _metadata_label_lines(scene, measurement):
    if scene is None or measurement is None:
        return []

    lines = []
    if _label_enabled(scene, "scientia_label_show_code", False):
        code = (getattr(measurement, "code", "") or "").strip()
        lines.append(f"code {code or 'no code'}")
    if _label_enabled(scene, "scientia_label_show_name", False):
        name = (getattr(measurement, "name", "") or "").strip()
        if name:
            lines.append(f"name {name}")
    if _label_enabled(scene, "scientia_label_show_description", False):
        description = (getattr(measurement, "description", "") or "").strip()
        if description:
            lines.append(description)
    return lines


def _label_enabled(scene, property_name, default):
    if scene is None:
        return default
    return bool(getattr(scene, property_name, default))


def _point_angle_degrees(points):
    try:
        start, center, end = points[:3]
        return math.degrees((start - center).angle(end - center))
    except Exception:
        return 0.0


def _draw_label_background_2d(blf, font_id, lines, x, y):
    if not lines:
        return
    try:
        widths = [blf.dimensions(font_id, line)[0] for line in lines]
    except Exception:
        widths = [len(line) * 7 for line in lines]
    width = max(widths, default=0.0) + 8
    height = len(lines) * 14 + 4
    _draw_filled_rect_2d(x - 4, y - height + 10, width, height, (0.05, 0.05, 0.05, 0.62))


def _draw_filled_rect_2d(x, y, width, height, color):
    import gpu
    from gpu_extras.batch import batch_for_shader

    shader = _uniform_color_shader(gpu)
    if shader is None:
        return
    coords = (
        (x, y),
        (x + width, y),
        (x + width, y + height),
        (x, y + height),
    )
    indices = ((0, 1, 2), (0, 2, 3))
    try:
        gpu.state.blend_set('ALPHA')
    except Exception:
        pass
    batch = batch_for_shader(shader, 'TRIS', {"pos": coords}, indices=indices)
    shader.bind()
    shader.uniform_float("color", color)
    batch.draw(shader)


def active_measurement_record(scene):
    try:
        index = getattr(scene, "scientia_active_measurement_index", -1)
        if index < 0 or index >= len(scene.scientia_measurements):
            return None
        measurement = scene.scientia_measurements[index]
        points = [_vector(point.co) for point in measurement.points]
        if len(points) == 2:
            return active_linear_record_from_points(points, scene, measurement)
        if len(points) >= 3:
            return active_plane_record_from_points(points, scene, measurement)
    except Exception:
        return None
    return None


def _record_cache_key(kind, points, scene, measurement):
    return (
        kind,
        tuple((float(point.x), float(point.y), float(point.z)) for point in points),
        float(getattr(scene, "az_real", 0.0)),
        float(getattr(scene, "az_model", 0.0)),
        getattr(measurement, "layer", "Default"),
    )


def _cached_record(key, factory):
    """Memoize processed records used by the viewport overlay.

    Labels are rebuilt on every viewport redraw, and a plane record runs an
    iterative eigen decomposition, so an unmemoized overlay cost one solve per
    polygon per frame.
    """
    record = _record_cache.get(key)
    if record is not None:
        return record
    record = factory()
    if record is not None:
        if len(_record_cache) >= RECORD_CACHE_LIMIT:
            _record_cache.clear()
        _record_cache[key] = record
    return record


def clear_record_cache():
    _record_cache.clear()


def active_linear_record_from_points(points, scene, measurement):
    try:
        key = _record_cache_key("linear", points[:2], scene, measurement)
    except Exception:
        key = None

    def _build():
        try:
            raw = RawMeasurement(
                kind=MeasurementKind.LINEAR,
                points=tuple(Point3D(point.x, point.y, point.z) for point in points[:2]),
                source="ScientiaScene",
                source_id=getattr(measurement, "uuid", ""),
                layer=getattr(measurement, "layer", "Default"),
            )
            correction = AzimuthCorrection(
                az_real=getattr(scene, "az_real", 0.0),
                az_model=getattr(scene, "az_model", 0.0),
            )
            return process_linear_measurement(raw, correction)
        except Exception:
            return None

    return _build() if key is None else _cached_record(key, _build)


def active_plane_record_from_points(points, scene, measurement):
    try:
        key = _record_cache_key("plane", points, scene, measurement)
    except Exception:
        key = None

    def _build():
        try:
            raw = RawMeasurement(
                kind=MeasurementKind.PLANE,
                points=tuple(Point3D(point.x, point.y, point.z) for point in points),
                source="ScientiaScene",
                source_id=getattr(measurement, "uuid", ""),
                layer=getattr(measurement, "layer", "Default"),
            )
            correction = AzimuthCorrection(
                az_real=getattr(scene, "az_real", 0.0),
                az_model=getattr(scene, "az_model", 0.0),
            )
            return process_plane_measurement(raw, correction)
        except Exception:
            return None

    return _build() if key is None else _cached_record(key, _build)


def _measurement_color(measurement, index, scene):
    hover_index, hover_part, _hover_point = _active_preview["hover"]
    if index == getattr(scene, "scientia_active_measurement_index", -1):
        return scene_measure_active_color(scene)
    if index == hover_index and hover_part:
        return (1.0, 1.0, 1.0, 1.0)
    code_color = scene_measurement_code_color(scene, getattr(measurement, "code", ""))
    if code_color is not None:
        return code_color
    return tuple(getattr(measurement, "color", scene_measure_default_color(scene)))


def _measurement_visible(scene, measurement, index=None):
    # The active measurement always stays visible: a fresh measurement starts
    # as a 2-point linear one and must not vanish mid-edit when its kind or
    # code group is hidden.
    if index is not None and index == getattr(scene, "scientia_active_measurement_index", -1):
        return True
    if not scene_measurement_code_visible(scene, getattr(measurement, "code", "")):
        return False
    return _measurement_kind_visible(scene, measurement)


def _measurement_kind_visible(scene, measurement):
    """Viewport-only filter by measurement kind; does not affect export."""
    if len(getattr(measurement, "points", ())) == 2:
        return bool(getattr(scene, "scientia_measure_show_linear", True))
    return bool(getattr(scene, "scientia_measure_show_planes", True))


def _handle_measurement_indices(scene):
    if getattr(scene, "scientia_measure_show_all_handles", False):
        return range(len(scene.scientia_measurements))

    indices = []
    active_index = getattr(scene, "scientia_active_measurement_index", -1)
    if active_index >= 0:
        indices.append(active_index)

    hover_index, _hover_part, _hover_point = _active_preview["hover"]
    if hover_index >= 0 and hover_index not in indices:
        indices.append(hover_index)

    return tuple(indices)


def _uniform_color_shader(gpu):
    for name in ("UNIFORM_COLOR", "3D_UNIFORM_COLOR"):
        try:
            return gpu.shader.from_builtin(name)
        except Exception:
            continue
    return None


def _segments(points, closed=False):
    if len(points) == 2:
        return ((points[0], points[1]),)
    segments = [(points[index], points[index + 1]) for index in range(len(points) - 1)]
    if closed and len(points) >= 3:
        segments.append((points[-1], points[0]))
    return tuple(segments)


def _distance_to_segment_2d(point, start, end):
    segment = end - start
    length_squared = segment.length_squared
    if length_squared == 0:
        return (point - start).length
    factor = max(0.0, min(1.0, (point - start).dot(segment) / length_squared))
    projection = start + segment * factor
    return (point - projection).length


def _closest_point_on_segment(point, start, end):
    segment = end - start
    length_squared = segment.length_squared
    if length_squared <= 0:
        return start.copy()
    factor = max(0.0, min(1.0, (point - start).dot(segment) / length_squared))
    return start + segment * factor


def _average_point(points):
    if not points:
        return None
    total = points[0].copy()
    for point in points[1:]:
        total += point
    return total / len(points)


def _vector(value):
    from mathutils import Vector

    if hasattr(value, "x"):
        return Vector((value.x, value.y, value.z))
    return Vector((value[0], value[1], value[2]))


def _angle_arc_points(start, center, end):
    v1 = start - center
    v2 = end - center
    len1 = v1.length
    len2 = v2.length
    if len1 <= MIN_MEASUREMENT_LENGTH or len2 <= MIN_MEASUREMENT_LENGTH:
        return ()

    radius = min(len1, len2) * 0.25
    if radius <= MIN_MEASUREMENT_LENGTH:
        return ()

    try:
        axis = v1.cross(v2)
        if axis.length <= MIN_MEASUREMENT_LENGTH:
            return ()
        angle = v1.angle(v2)
        if angle <= 1.0e-6:
            return ()
        axis.normalize()
        direction = v1.normalized()
        from mathutils import Matrix
        arc = []
        for step in range(ANGLE_ARC_SEGMENTS + 1):
            factor = step / ANGLE_ARC_SEGMENTS
            rotated = Matrix.Rotation(angle * factor, 4, axis) @ direction
            arc.append(center + rotated * radius)
        return tuple(arc)
    except Exception:
        return ()


def _measurement_is_polygon(measurement, points):
    return len(points) > 3 or str(getattr(measurement, "kind", "") or "").upper() == "POLYLINE"


def _polygon_preview_points(include_current=False):
    points = list(_polygon_preview["points"])
    current = _polygon_preview["current"]
    if include_current and current is not None:
        if len(points) >= 3 and (current - points[0]).length <= MIN_MEASUREMENT_LENGTH:
            return points
        if not points or (current - points[-1]).length > MIN_MEASUREMENT_LENGTH:
            points.append(current)
    return points


def _screen_distance_to_point(context, event, point):
    from bpy_extras import view3d_utils
    from mathutils import Vector

    position = view3d_utils.location_3d_to_region_2d(context.region, context.region_data, point)
    if position is None:
        return float("inf")
    mouse = Vector((event.mouse_region_x, event.mouse_region_y))
    return (mouse - position).length


def _reset_preview():
    _active_preview["points"] = ()
    _active_preview["snap"] = False
    _active_preview["snap_type"] = None
    _active_preview["hover"] = (-1, None, -1)
    _active_preview["snap_location"] = None


def _reset_polygon_preview():
    _polygon_preview["points"] = ()
    _polygon_preview["current"] = None
    _polygon_preview["snap"] = False
    _polygon_preview["snap_type"] = None
    _polygon_preview["snap_location"] = None
    _polygon_preview["closing"] = False


def _snap_enabled(scene, event):
    snap_by_default = bool(getattr(scene, "scientia_measure_snap_by_default", False))
    return snap_by_default != bool(getattr(event, "ctrl", False))


def _cursor_for_state(ctrl, snapped, mode):
    if snapped:
        return 'EYEDROPPER'
    if ctrl:
        return 'CROSSHAIR'
    if mode in {"edit_point", "add_center"}:
        return 'MOVE_X'
    return 'CROSSHAIR'


def _set_cursor(context, cursor):
    try:
        context.window.cursor_modal_set(cursor)
    except Exception:
        pass


def _restore_cursor(context):
    try:
        context.window.cursor_modal_restore()
    except Exception:
        pass


def _tag_view3d_redraw(context):
    screen = getattr(context, "screen", None)
    if screen is None:
        return
    for area in screen.areas:
        if area.type == 'VIEW_3D':
            area.tag_redraw()
